/* This file is generated by the scripts in /config. */

#ifndef _OPEN64_TARGINFO_PROC                                                                        /* GENERATED */
#define _OPEN64_TARGINFO_PROC

/*****************************************************************************/
/* Pipeline organization                                                     */
/*****************************************************************************/

#define S_LAST 6
#define S_BR 3
#define S_FW 3
#define S_SRD 3                                                                                      /* GENERATED */
#define S_ALU 3
#define S_MEM 4
#define S_SWB 5
#define S_STOP 2
#define S_WB 5
#define L_MUL 2
#define L_BRK 0
#define S_BTGT 2
#define L_ALU1 0
#define S_TRAP 2                                                                                     /* GENERATED */
#define L_ALU2 1
#define L_WB 1
#define L_ALU 1
#define S_BRK 4
#define S_PCP1 1
#define L_MUL2 1
#define L_MEM 1
#define S_LTRP 5
#define S_RD 2
#define L_RD 1                                                                                       /* GENERATED */
#define L_IF 1
#define S_FIRST 1
#define S_MUL 3
#define S_IF 1
#define S_LIMM 2
#define L_MUL1 1
#define L_IF_MEM 1
#define S_SFW 3

#endif                                                                                               /* GENERATED */
