set_property direction OUT [get_ports {leds[0]}]
set_property direction OUT [get_ports {leds[1]}]
set_property direction OUT [get_ports {leds[2]}]
set_property direction OUT [get_ports {leds[3]}]
set_property direction OUT [get_ports {leds[4]}]
set_property direction OUT [get_ports {leds[5]}]
set_property direction OUT [get_ports {leds[6]}]
set_property direction OUT [get_ports {leds[7]}]
set_property direction IN [get_ports {resetButton}]
set_property direction IN [get_ports {rx}]
set_property direction IN [get_ports {sysclk_n}]
set_property direction IN [get_ports {sysclk_p}]
set_property direction OUT [get_ports {tx}]
make_diff_pair_ports sysclk_p sysclk_n
create_clock -period 5.000 -name sysclk_p -waveform {0.000 2.500} [get_ports sysclk_p]
#create_clock -period 5.000 -name sysclk_n -waveform {2.500 5.000} [get_ports sysclk_n]
set_property IOSTANDARD LVDS [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_n]
set_property PACKAGE_PIN E19 [get_ports sysclk_p]
set_property PACKAGE_PIN E18 [get_ports sysclk_n]
set_property PACKAGE_PIN AV40 [get_ports resetButton]
set_property PACKAGE_PIN AU36 [get_ports tx]
set_property PACKAGE_PIN AU33 [get_ports rx]
set_property PACKAGE_PIN AM39 [get_ports {leds[0]}]
set_property PACKAGE_PIN AN39 [get_ports {leds[1]}]
set_property PACKAGE_PIN AR37 [get_ports {leds[2]}]
set_property PACKAGE_PIN AT37 [get_ports {leds[3]}]
set_property PACKAGE_PIN AR35 [get_ports {leds[4]}]
set_property PACKAGE_PIN AP41 [get_ports {leds[5]}]
set_property PACKAGE_PIN AP42 [get_ports {leds[6]}]
set_property PACKAGE_PIN AU39 [get_ports {leds[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports resetButton]
set_property IOSTANDARD LVCMOS18 [get_ports rx]
set_property IOSTANDARD LVCMOS18 [get_ports tx]

