
# Toolchain setup.
TOOLS = ../../../tools
GEN_EXAMPLES = ../../../examples

# Platform-specific executables.
EXECUTABLES = 

# Platform-specific object files to link.
OBJECTS = rvex-grlib.o

# Platform specific targets for help.
TARGETS = 

# Include generic examples makefile.
include $(GEN_EXAMPLES)/Makefile

